### ISSUE TITLE
Start/End Time with hours in double digits causes error

### ISSUE THREAD

**Issue by jarrah31** [acockburn/occusim#13]
For some reason, the moment I set the start or end time to be 10:00:00 or higher, an error occurs. For example, the following works ok:
```
  step_evening_study_off_name: Evening Lights Off
  step_evening_study_off_start: 09:00:00
  step_evening_study_off_end: 09:40:00
  step_evening_study_off_off_1: light.ensuite
```
As soon as I save the file with the following increase in hours to double digits, the error below occurs:
```
  step_evening_study_off_name: Evening Lights Off
  step_evening_study_off_start: 09:00:00
  step_evening_study_off_end: 10:40:00
  step_evening_study_off_off_1: light.ensuite
```
Error:
```
2018-03-30 11:54:25.267428 WARNING AppDaemon: ------------------------------------------------------------
2018-03-30 11:54:25.268396 WARNING AppDaemon: Unexpected error running initialize() for Occupancy Simulator
2018-03-30 11:54:25.269287 WARNING AppDaemon: ------------------------------------------------------------
2018-03-30 11:54:25.271477 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 1513, in init_object
    init()
  File "/home/homeassistant/conf/apps/occusim.py", line 32, in initialize
    self.create_events({})
  File "/home/homeassistant/conf/apps/occusim.py", line 68, in create_events
    end = self.parse_time(end_p)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appapi.py", line 277, in parse_time
    return self.AD.parse_time(time_str, name)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/appdaemon.py", line 1015, in parse_time
    parts = re.search('^(\d+):(\d+):(\d+)', time_str)
  File "/usr/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

2018-03-30 11:54:25.272501 WARNING AppDaemon: ------------------------------------------------------------
```
I'm running Home Assistant on Hassbian with the following versions:
HA: 0.65.5
AppDaemon: 3.0.0
Occusim: 1.1.5

appdaemon.yaml:
```
log:
  # accessfile: /export/hass/appdaemon_test/logs/access.log
  errorfile: /home/homeassistant/conf/log/occusim_err.log
  logfile: /home/homeassistant/conf/log/occusim.log
  log_generations: 3
  log_size: 1000000
appdaemon:
  threads: 10
  # time_zone: <time zone>
  api_port: 5000
  plugins:
    HASS:
      type: hass
      ha_url: http://localhost:8123
      ha_key: !secret home_assistant_pass
```
apps.yaml - as you can see most steps work ok because their times are below 10:00:00, yet any that are 10 or above cause the error. 
```
Occupancy Simulator:
  class: OccuSim
  module: occusim
  log: '1'
  notify: '1'
  # enable: input_boolean.wearehome,off
  # test: '0'
  dump_times: '1'
  reset_time: 02:00:00

  step_morning_ensuite_on_name: Morning En-Suite On
  step_morning_ensuite_on_days: mon,tue,wed,thu,fri
  step_morning_ensuite_on_start: 06:00:00
  step_morning_ensuite_on_end: 06:15:00
  step_morning_ensuite_on_on_1: light.ensuite

  step_morning_ensuite_off_name: Morning En-Suite Off
  step_morning_ensuite_off_days: mon,tue,wed,thu,fri
  step_morning_ensuite_off_start: 06:30:00
  step_morning_ensuite_off_end: 07:00:00
  step_morning_ensuite_off_off_1: light.ensuite

  step_evening_ensuite_on_name: Evening En-Suite On
  step_evening_ensuite_on_relative: Evening Study Off
  step_evening_ensuite_on_start_offset: 00:05:00
  step_evening_ensuite_on_end_offset: 00:10:00
  step_evening_ensuite_on_on_1: light.ensuite

  step_evening_ensuite_off_name: Evening En-Suite Off
  step_evening_ensuite_off_relative: Evening En-Suite On
  step_evening_ensuite_off_start: 00:05:00
  step_evening_ensuite_off_end: 00:10:00
  step_evening_ensuite_off_off_1: light.ensuite

  # step_evening_study_on_name: Evening Study On
  # step_evening_study_on_start: sunset - 00:30:00
  # step_evening_study_on_end: sunset
  # step_evening_study_on_on_1: group.study_lamps

  step_evening_study_off_name: Evening Lights Off
  step_evening_study_off_start: 09:00:00
  step_evening_study_off_end: 10:40:00
  step_evening_study_off_off_1: light.ensuite
  # step_evening_study_off_off_1: group.study_lamps

  step_evening_hall_name: EveningHall
  step_evening_hall_start: sunset - 00:45:00
  step_evening_hall_end: sunset - 00:30:00
  step_evening_hall_on_1: group.hall_lights
  #
  # step_night_hall_name: NightHall
  # step_night_hall_start: 22:00:00
  # step_night_hall_end: 22:20:00
  # step_night_hall_off_1: group.hall_lights
```

**Comment by acockburn** [comment]
Try enclosing the problem times in quotes, e.g.:

```yaml
step_night_hall_start: "22:00:00"
```

**Comment by jarrah31** [comment]
Thank you, that solved the problem!
