### ISSUE TITLE
KeyError on random tasks

### ISSUE THREAD

**Issue by ghost** [acockburn/occusim#4]
Hi there, 

got an KeyError when i try to use random tasks:

```
2017-04-13 19:04:51.038146 WARNING ------------------------------------------------------------
2017-04-13 19:04:51.039209 WARNING Logged an error to /home/osmc/.homeassistant/home-assistant-appdaemon.log
2017-04-13 19:04:59.008986 INFO /home/osmc/.homeassistant/appdaemon.cfg modified
2017-04-13 19:04:59.024273 INFO App 'Occupancy Simulator' changed - reloading
2017-04-13 19:04:59.026313 INFO Loading Object Occupancy Simulator using class OccuSim from module occusim
2017-04-13 19:04:59.031195 WARNING ------------------------------------------------------------
2017-04-13 19:04:59.032585 WARNING Unexpected error:
2017-04-13 19:04:59.033617 WARNING ------------------------------------------------------------
2017-04-13 19:04:59.035363 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 913, in check_config
    new_config[name]["module"], new_config[name]
  File "/usr/local/lib/python3.4/dist-packages/appdaemon/appdaemon.py", line 690, in init_object
    conf.objects[name]["object"].initialize()
  File "/home/osmc/.homeassistant/apps/occusim.py", line 31, in initialize
    self.create_events({})
  File "/home/osmc/.homeassistant/apps/occusim.py", line 157, in create_events
    starttime = events[startstep]["event"]
KeyError: '05:30:00'
```

My config, just out of your example:
```
[Occupancy Simulator]
module = occusim
class = OccuSim
log = 1
notify = 0
enable = input_boolean.vacation,off
test = 1

random_morning_name = Morning
random_morning_days = mon,tue,wed,thu,fri
random_morning_start = 05:30:00
random_morning_end = 06:00:00
random_morning_on_1 = event.MODE_CHANGE,mode
````
Sequenced tasks seem to work fine. Tried sunset, sunrise, morning, eventing, ... Error still just occour on randoms.

**Comment by acockburn** [comment]
Hi there - 

Random's don;t take times and days etc. as arguments, they operate between 2 predefined steps.

Fromm the docs:

To set up a random event, it is first necessary to define 2 steps to act as the start and end times for the random activity. The steps themselves need not do turn anything on or off, they are there as markers.

**Comment by ghost** [comment]
Uhh, my gosh. 
Now i got that. Had to read that more than twice to understand. Thanks for the fast response!
